name: 'Workflow Configuration from Python'
description: |
  Clone the repository, and invoke a Python function to generate
  dynamic configuration settings for a workflow.
inputs:
  clone-dir:
    description: |
      Local directory where the repository will be cloned.
  github:
    description: |
      A JSON serialization of the `github` context.
    required: true
  inputs:
    description: |
      A JSON serialization of the `inputs` context.
    required: true
runs:
  using: "composite"
  steps:
    - name: Clone source repository
      uses: actions/checkout@v4
      with:
        path: ${{ inputs.clone-dir }}
        submodules: true

    - name: Generate workflow configuration
      id: config
      shell: python
      run: |
        import json
        import sys
        import importlib
        from pathlib import Path

        clone_dir = Path("${{ inputs.clone-dir }}")

        github = json.loads("""\
          ${{ inputs.github }}
        """)

        inputs = json.loads("""\
          ${{ inputs.inputs }}
        """)

        workflow_name = github["workflow"]

        sys.path.insert(0, "${{ inputs.clone-dir }}/scripts")
        module = importlib.import_module(
          f"action_helpers.workflows.{workflow_name}")

        module.configure(clone_dir=clone_dir, github=github, inputs=inputs)
